sudo: required
language: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

before_install:
  - sudo apt-get update
  - eval "${MATRIX_EVAL}"
install: ./install.sh
script: ant test
after_script: ./uninstall.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
